### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-59b3k#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by metalandcoffee** [comment]
To be implemented... load the `placeholder.png` when there is no image for a product.

**Comment by metalandcoffee** [comment]
Fix screenshot:
![image](https://user-images.githubusercontent.com/20868511/195220885-a8603414-d8e7-47ff-8558-25cc1287bd0d.png)
